### PR TITLE
add a "Syncthing INotify" switch

### PR DESCRIPTION
**Pull request by Palatis**
toggles the syncthing-inotify.service

### CODE REVIEW

**Comment by jaystrictor** [comment]
Hmm, I already had a discussion about that topic with @rumpelsepp on the [Syncthing forum](https://forum.syncthing.net/t/gnome-shell-extension-syncthing-icon/5759/3).
Since [this patch](https://github.com/syncthing/syncthing/pull/2312), syncthing-inotify is started and stopped with syncthing. So I don't see the need to add another switch.

Please feel free to convince me otherwise, ...

**Comment by Palatis** [comment]
syncthing.service and syncthing-inotify.service are different service.
sometimes user forget to install the inotify service, but syncthing still gonna work (it just have to do the periodical scanning before it knows some file changed).

I think having a switch there to indicate service status is a good idea, anyway.

**Comment by jaystrictor** [comment]
Sorry, I don't want to merge this.
I have the impression that the issue you describe would better be addressed by giving the user a unobtrusive notification that syncthing-inotify is not running/not available. I don't see the need for a second on/off switch.

**Comment by Palatis** [comment]
so, would you accept an inotify service indicator?
like it just tell the user if the inotify service is installed/running or not, but unable to control the on/off state of the service?

the user will have to issue `systemctl --user start/stop syncthing-inotify` somewhere else to control the service status.

**Comment by Palatis** [comment]
and maybe just hide the message if the inotify service is up and running.

in a "no smoke, no problem." manner.

**Comment by jaystrictor** [comment]
Yes, seems like a good idea.
Thank you for working on that.

**Comment by jaystrictor** [comment]
Also note that the user will **not** have to issue `systemctl --user start/stop syncthing-inotify` manually, simply because if `syncthing-inotify.service` is available, it is started and stopped with `syncthing.service`.

**Comment by Palatis** [comment]
I mean, we can't imagine how user would like to use the program.
Maybe he/she wants to start syncthing **without** the inotify service?
Although I can't think of a case that anyone would do that, but... Who knows!

**Comment by jaystrictor** [comment]
True, we can't know for sure in what ways users would like to use the extension.
We can however assume that they want to use it in a resource-efficient way, so usually they would want to have inotify. As long as we assume that, we should not add the option to disable inotify.

Furthermore, the syncthing team plans to [merge inotify into syncthing](https://github.com/syncthing/syncthing/pull/2807). When this is done, the second switch would be obsolete.

**Pull request closed without merging**
