### PR TITLE
Symbols/Signs for compatibility

### PR DESCRIPTION
**Pull request by KopfKrieg**
More or less a fix for issue #12 

I simply replaced the unicode characters with symbols almost every font has included. Maybe you want to merge it. If not, well, then not :)

### CODE REVIEW

**Comment by jaystrictor** [comment]
Hmm, I have been there, done that. Didn't look so good.

I would prefer a proper SVG icon file to replace each of these letters. That way there are no missing glyphs.

**Comment by KopfKrieg** [comment]
> Hmm, I have been there, done that. Didn't look so good.

Oh, sorry, didn't know that.

I'm not sure if this is possible, but if there's a way to force a specific font within gnome shell extensions maybe the (font-awesome project)[https://fortawesome.github.io/Font-Awesome/icons/] might be worth a look. I'm not completely sure, but I think it's possible to extract svg-icons from the project (Can't test it right now, got a very slow and crappy internet connection at the moment).

**Comment by jaystrictor** [comment]
Ah yes, that's a really nice idea.
Looking into it now.

**Comment by jaystrictor** [comment]
@KopfKrieg FontAwesome glyphs are now used in current master.
Feedback is welcome.

**Pull request closed without merging**
